-- 插入測試數據（使用大寫表名）
INSERT INTO GRPC_PROXY_MAP (
    service_name,
    proxy_hostname,
    target_hostname,
    target_port,
    connect_timeout_ms,
    send_timeout_ms,
    read_timeout_ms,
    secure_mode,
    auto_trust_upstream_certs,
    enable,
    create_date_time,
    create_user,
    version
) VALUES
      (
          'test-service',
          'api.test.com',
          'backend.test.com',
          8080,
          5000,
          10000,
          30000,
          'AUTO',
          'N',
          'Y',
          CURRENT_TIMESTAMP,
          'SYSTEM',
          1
      ),
      (
          'user-service',
          'users.api.com',
          'users-backend.internal',
          9090,
          5000,
          10000,
          30000,
          'PLAINTEXT',
          'N',
          'Y',
          CURRENT_TIMESTAMP,
          'SYSTEM',
          1
      );